
import { createI18n } from 'vue-i18n';

const messages = {
  en: {
    header_title:'AI Poem Generator - Create a rhyming poem with free AI poem generator',
    Description:"A free AI poem generator that anyone can create a rhyming poem in seconds. Explore our AI Poem Generator: Create custom, rhyming poems on any poem theme.",
    "poemai_title": "AI Poem Generator",
    "poemai_input_title": "AI Poem Generator",
    "poemai_input_subtitle": "Generate a poem about...",
    "poemai_input_tips": "The Journey of a Wandering Cloud",
    "poemai_generate_btn": "Generate Poem",
    "poemai_powered_by_gpt": "Powered By ChatGPT",
    "poemai_thinking_status": "Thinking...",
    "poemai_network_err_toast": "Network error. Try again plz",
    "poemai_server_err_toast": "Server error, please try again",
    "poemai_generated_failed_toast": "Failed to generate poem, please try again",
    "poemai_generated_poem": "Generated Poem",
    "poemai_copy_btn": "Copy",
    "poemai_copy_success_toast": "Copied successfully",
    "poemai_privacy": "Privacy Policy",
    poemai_title_generate:"Generate",
    privacy:{
      t1:"Privacy Policy",
      c1:`Last updated: January 5, 2024
      This Privacy Policy outlines our policies and procedures on the collection, use, and disclosure of your information when you use the Service and informs you about your privacy rights and how the law protects you.
      We utilize your personal data to provide and enhance the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.`,
      t2:"Interpretation and Definitions",
      t2_1:"Interpretation",
      c2_1:`The words with the initial letter capitalized have meanings defined under the following conditions. These definitions shall have the same meaning whether they appear in singular or plural.`,
      t2_2:"Definitions",
      c2_2:"For the purposes of this Privacy Policy:",
      u2_2:[
        {b:'Account',l:"refers to a unique account created for you to access our service or parts of our service."},
        {b:'Company',l:`(referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to Ai Poem Generator.`},
        {b:'Cookies',l:"are small files placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses."},
        {b:'Device',l:"means any device that can access the Service such as a computer, a cellphone, or a digital tablet."},
        {b:'Personal Data',l:"is any information related to an identified or identifiable individual."},
        {b:'Service',l:"refers to the Website."},
        {b:'Service Provider',l:"means any natural or legal person who processes data on behalf of the Company. This refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used."},
        {b:'Usage Data',l:"refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."},
        {b:'Website',l:"refers to Ai Poem Generator, accessible from https://poemgenerator-ai.com/"},
        {b:'You',l:"mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."},
      ],
      t3:'Collecting and Using Your Personal Data',
      t3_1:'Types of Data Collected',
      t3_1_1:'Personal Data',
      c3_1_1:"While using Our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:",
      u3:['Email address','Usage Data'],
      t3_1_2:'Usage Data',
      c3_1_2:`Usage Data is collected automatically when using the Service.
      Use of Data may include information such as your device's Internet Protocol address (e.g., IP address), browser type, version, pages visited on our service, visit time and date, time spent on those pages, unique device identifiers, and other diagnostic data.
      When you access the service via a mobile device, we may automatically collect certain information, including but not limited to, the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile internet browser you use, unique device identifiers, and other diagnostic data.
      We may also collect information sent by your browser when you visit our service or when you access the service via a mobile device.`,
      t3_1_3:"Tracking Technologies and Cookies",
      c3_1_3:"We use Cookies and similar tracking technologies to track activities on our service and store certain information. The tracking technologies employed are beacons, tags, and scripts to collect and track information and to improve and analyze our service. The technologies we use may include:",
      u3_1_3:[
        {b:'Cookies or Browser Cookies.',l:"A cookie is a small file placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our service. Unless you have adjusted your browser setting to refuse cookies, our service may use cookies."},
        {b:'Web Beacons.',l:"Some sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that allow the company, for example, to count users who have visited those pages or opened an email and other related website statistics (such as recording the popularity of a certain section and verifying system and server integrity)."}
      ],
      c3_1_3_1:`Cookies can be "Persistent" or "Session" based. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser.
      We use both session and persistent cookies for the purposes outlined below:`,
      u3_1_3_1:[
        {b:'Necessary/Essential Cookies',l:'Type: Session Cookies Administered by: Us Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services you have requested cannot be provided, and we only use these cookies to provide you with those services.'},{b:'Cookies Policy/Notice Acceptance Cookies',l:'Type: Persistent Cookies Administered by: Us Purpose: These cookies identify if users have accepted the use of cookies on the website.'},{b:'Functionality Cookies',l:'TType: Persistent Cookies Administered by: Us Purpose: These cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.'},
      ],
      c3_1_3_2:"For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.",
      t3_2:"Use of Your Personal Data",
      c3_2:"The Company may use Personal Data for the following purposes:",
      u3_2:[
        {b:'To provide and maintain our Service,',l:'including to monitor the usage of our Service.'},
        {b:'To manage Your Account:',l:"to manage your registration as a user of the Service. The Personal Data you provide can grant you access to different functionalities of the Service available to you as a registered user."},
        {b:'For the performance of a contract:',l:"the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or any other contract with us through the Service."},
        {b:'To contact You:',l:"To reach out to you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as mobile application's push notifications regarding updates or informative communications related to functionalities, products, or contracted services, including necessary security updates."},
        {b:'To manage Your requests:',l:"To attend and manage your requests to us."},
        {b:'For business transfers:',l:"We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or any other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our Service users is among the assets transferred."},
        {b:'For other purposes:',l:"We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, marketing, and your experience."},
      ],
      c3_2_1:'We may share Your personal information in the following situations:',
      u3_2_1:[
        {b:'With Service Providers:',l:'We may share your personal information with Service Providers to monitor and analyze the use of our Service, and to contact you.'},
        {b:'For business transfers:',l:'We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.'},
        {b:'With Affiliates:',l:'We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.'},
        {b:'With business partners:',l:'We may share your information with our business partners to offer you certain products, services, or promotions.'},
        {b:'With other users:',l:'When you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.'},
        {b:'With your consent:',l:'We may disclose your personal information for any other purpose with your consent.'},
      ],
      t3_3:'Retention of Your Personal Data',
      c3_3:`The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
      The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.`,
      t3_4:'Transfer of Your Personal Data',
      c3_4:`Your information, including Personal Data, will be processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
      Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.`,
      t3_5:'Deletion of Your Personal Data',
      c3_5:`You have the right to delete or request our assistance in deleting the personal data we have collected about you.
      Our service may allow you to delete certain information about yourself from within the service.
      You can update, amend, or delete your information at any time by logging into your account (if you have one) and accessing the account settings section to manage your personal information. You can also contact us to request access to, correction of, or deletion of any personal information you have provided to us.
      However, please note that we may need to retain certain information when we have a legal obligation or a lawful basis to do so.`,
      t3_6:'Disclosure of Your Personal Data',
      t3_6_1:'Business Transactions',
      c3_6_1:'If the Company is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.',
      t3_6_2:'Law Enforcement',
      c3_6_2:'Under certain circumstances, the Company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or government agency).',

    }
  },
  fr: {
    header_title:"Générateur de poèmes - Créez un poème rimé avec l'IA gratuite",
    Description:"Un générateur de poèmes IA gratuit permettant de créer rapidement des poèmes rimés. Explorez notre générateur pour des poèmes personnalisés sur tout thème.",
    "poemai_title": "Générateur de poème",
    "poemai_input_title": "Générateur de poème",
    "poemai_input_subtitle": "Générer un poème sur...",
    "poemai_input_tips": "Première neige sur la montagne",
    "poemai_generate_btn": "Générer",
    "poemai_powered_by_gpt": "Propulsé par ChatGPT",
    "poemai_thinking_status": "Réflexion...",
    "poemai_network_err_toast": "Erreur réseau. Réessayez svp",
    "poemai_server_err_toast": "Erreur du serveur, veuillez réessayer",
    "poemai_generated_failed_toast": "Échec de la génération du poème, veuillez réessayer",
    "poemai_generated_poem": "Poème généré",
    "poemai_copy_btn": "Copier",
    "poemai_copy_success_toast": "Copié avec succès",
    "poemai_privacy": "Politique de confidentialité",
    poemai_title_generate:"Générer"
  },
  ru: {
    header_title:"Генератор стихов - создайте рифму с бесплатным AI",
    Description:"Бесплатный генератор стихов на ИИ: создание рифмованных стихов в секунды. Откройте наш генератор и напишите красивое стихотворение.",
    "poemai_title": "Генератор Стихов",
    "poemai_input_title": "Генератор Стихов",
    "poemai_input_subtitle": "Сгенерировать стих о...",
    "poemai_input_tips": "Ветер в поле звенит",
    "poemai_generate_btn": "Генерировать",
    "poemai_powered_by_gpt": "На платформе ChatGPT",
    "poemai_thinking_status": "Думаю...",
    "poemai_network_err_toast": "Ошибка сети. Попробуйте еще раз",
    "poemai_server_err_toast": "Ошибка сервера, попробуйте еще раз",
    "poemai_generated_failed_toast": "Не удалось сгенерировать стих, попробуйте еще раз",
    "poemai_generated_poem": "Сгенерированный стих",
    "poemai_copy_btn": "Копировать",
    "poemai_copy_success_toast": "Успешно скопировано",
    "poemai_privacy": "Политика конфиденциальности",
    poemai_title_generate:"Генерировать"
  },
  de: {
    header_title:"Gedichten Generator - Kostenloses KI-Magie-Tool für Reimgedichte",
    Description:"Kostenloser AI-Gedichten Generator: Erstellen Sie Reimgedichte in Sekundenschnelle. Entdecken Sie unseren Generator und erstellen Sie Reimgedichte zu jedem Thema.",
    "poemai_title": "Gedichten Generator",
    "poemai_input_title": "Gedichten Generator",
    "poemai_input_subtitle": "Generiere ein Gedicht über...",
    "poemai_input_tips": "Herbstwind in den alten Gassen",
    "poemai_generate_btn": "Generieren",
    "poemai_powered_by_gpt": "Angetrieben von ChatGPT",
    "poemai_thinking_status": "Denken...",
    "poemai_network_err_toast": "Netzwerkfehler. Bitte versuchen Sie es erneut",
    "poemai_server_err_toast": "Serverfehler, bitte versuchen Sie es erneut",
    "poemai_generated_failed_toast": "Gedicht konnte nicht generiert werden, bitte versuchen Sie es erneut",
    "poemai_generated_poem": "Generiertes Gedicht",
    "poemai_copy_btn": "Kopieren",
    "poemai_copy_success_toast": "Erfolgreich kopiert",
    "poemai_privacy": "Datenschutzrichtlinie",
    poemai_title_generate:"Generieren"
  },
  it: {
    header_title:"Generatore di poesie - Crea poesie in rima con l'AI gratuito",
    Description:"Un generatore gratuito di poesie AI per creare poesie in rima in pochi secondi. Esplora il nostro Generatore di Poesie AI: crea poesie personalizzate su qualsiasi tema.",
    "poemai_title": "Generatore di poesie",
    "poemai_input_title": "Generatore di poesie",
    "poemai_input_subtitle": "Genera una poesia su...",
    "poemai_input_tips": "Baci sotto la pioggia",
    "poemai_generate_btn": "Genera",
    "poemai_powered_by_gpt": "Alimentato da ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Errore di rete. Riprova per favore",
    "poemai_server_err_toast": "Errore del server, riprova",
    "poemai_generated_failed_toast": "Generazione della poesia fallita, riprova",
    "poemai_generated_poem": "Poesia generata",
    "poemai_copy_btn": "Copia",
    "poemai_copy_success_toast": "Copiato con successo",
    "poemai_privacy": "Politica sulla privacy",
    poemai_title_generate:"Generare"
  },
  pt: {
    header_title:"Gerador de Poemas - Crie um poema rimado com a mágica AI gratuita",
    Description:"Gerador de poemas AI gratuito: crie poemas rimados em segundos. Explore nosso Gerador de Poemas AI: Crie poemas rimados e personalizados sobre qualquer assunto.",
    "poemai_title": "Gerador de Poemas",
    "poemai_input_title": "Gerador de Poemas",
    "poemai_input_subtitle": "Gerar um poema sobre...",
    "poemai_input_tips": "Dança das flores silvestres",
    "poemai_generate_btn": "Gerar",
    "poemai_powered_by_gpt": "Alimentado por ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Erro de rede. Tente novamente",
    "poemai_server_err_toast": "Erro no servidor, tente novamente",
    "poemai_generated_failed_toast": "Falha ao gerar poema, tente novamente",
    "poemai_generated_poem": "Poema Gerado",
    "poemai_copy_btn": "Copiar",
    "poemai_copy_success_toast": "Copiado com sucesso",
    "poemai_privacy": "Política de privacidade",
    poemai_title_generate:"Gerar"
  },
  es: {
    header_title:"Generador de poemas - crea poemas que riman con AI Magic gratis",
    Description:"Generador de poemas AI gratuito: crea poemas rimados en segundos. Explora nuestro Generador de Poemas AI: Crea poemas rimados y personalizados sobre cualquier tema.",
    "poemai_title": "Generador de Poemas",
    "poemai_input_title": "Generador de Poemas",
    "poemai_input_subtitle": "Generar un poema sobre...",
    "poemai_input_tips": "Voces del bosque antiguo",
    "poemai_generate_btn": "Generar",
    "poemai_powered_by_gpt": "Impulsado por ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Error de red. Intente de nuevo por favor",
    "poemai_server_err_toast": "Error de servidor, intenta de nuevo",
    "poemai_generated_failed_toast": "Error al generar el poema, intenta de nuevo",
    "poemai_generated_poem": "Poema Generado",
    "poemai_copy_btn": "Copiar",
    "poemai_copy_success_toast": "Copiado con éxito",
    "poemai_privacy": "Política de privacidad",
    poemai_title_generate:"Generar"
  }
}


const i18n = createI18n({
  locale: 'en', // 默认语言
  fallbackLocale: 'en',
  messages,
});

export default i18n;