
import { createI18n } from 'vue-i18n';

const messages = {
  en: {
    header_title:'AI Poem Generator - Create a rhyming poem with free AI poem generator',
    Description:"A free AI poem generator that anyone can create a rhyming poem in seconds. Explore our AI Poem Generator: Create custom, rhyming poems on any poem theme.",
    "poemai_title": "AI Poem Generator",
    "poemai_input_title": "AI Poem Generator",
    "poemai_input_subtitle": "Generate a poem about...",
    "poemai_input_tips": "The Journey of a Wandering Cloud",
    "poemai_generate_btn": "Generate Poem",
    "poemai_powered_by_gpt": "Powered By ChatGPT",
    "poemai_thinking_status": "Thinking...",
    "poemai_network_err_toast": "Network error. Try again plz",
    "poemai_server_err_toast": "Server error, please try again",
    "poemai_generated_failed_toast": "Failed to generate poem, please try again",
    "poemai_generated_poem": "Generated Poem",
    "poemai_copy_btn": "Copy",
    "poemai_copy_success_toast": "Copied successfully",
    "poemai_privacy": "Privacy Policy",
    poemai_title_generate:"Generate",
    poemai_fv_theme:"What is the poem about?",
    privacyContent:`<h1>Privacy Policy</h1>
    <p>Last updated: January 5, 2024</p>
    <p>This Privacy Policy outlines our policies and procedures on the collection, use, and disclosure of your information when you use the Service and informs you about your privacy rights and how the law protects you.</p>
    <p>We utilize your personal data to provide and enhance the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>
    
    <h1>Interpretation and Definitions</h1>
    <h2>Interpretation</h2>
    <p>The words with the initial letter capitalized have meanings defined under the following conditions. These definitions shall have the same meaning whether they appear in singular or plural.</p>
    
    <h2>Definitions</h2>
    <p>For the purposes of this Privacy Policy:</p>
    
    <ul>
      <li><b>Account</b> refers to a unique account created for you to access our service or parts of our service.</li>
      <li><b>Company</b> (referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to Ai Poem Generator.</li>
      <li><b>Cookies</b> are small files placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses.</li>
      <li><b>Device</b> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
      <li><b>Personal Data</b> is any information related to an identified or identifiable individual.</li>
      <li><b>Service</b> refers to the Website.</li>
      <li><b>Service Provider</b> means any natural or legal person who processes data on behalf of the Company.</li>
      <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
      <li><b>Website</b> refers to Ai Poem Generator, accessible from <a link="https://poemgenerator-ai.com/">https://poemgenerator-ai.com/</a></li>
      <li><b>You</b> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    
    <h1>Collecting and Using Your Personal Data</h1>
    
    <h2>Types of Data Collected</h2>
    
    <h3>Personal Data</h3>
    <p>While using Our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
    <ul>
      <li>Email address</li>
      <li>Usage Data</li>
    </ul>
    
    <h3>Usage Data</h3>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Use of Data may include information such as your device's Internet Protocol address (e.g., IP address), browser type, version, pages visited on our service, visit time and date, time spent on those pages, unique device identifiers, and other diagnostic data.</p>
    <p>When you access the service via a mobile device, we may automatically collect certain information, including but not limited to, the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile internet browser you use, unique device identifiers, and other diagnostic data.</p>
    <p>We may also collect information sent by your browser when you visit our service or when you access the service via a mobile device.</p>
    
    <h3>Tracking Technologies and Cookies</h3>
    <p>We use Cookies and similar tracking technologies to track activities on our service and store certain information. The tracking technologies employed are beacons, tags, and scripts to collect and track information and to improve and analyze our service.</p>
    
    <p>The technologies we use may include:</p>
    <ul>
      <li><b>Cookies or Browser Cookies.</b> A cookie is a small file placed on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</li>
      <li><b>Web Beacons.</b> Some sections of our service and our emails may contain small electronic files known as web beacons.</li>
    </ul>
    
    <p>Cookies can be "Persistent" or "Session" based. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser.</p>
    
    <p>We use both session and persistent cookies for the purposes outlined below:</p>
    
    <ul>
      <li><b>Necessary/Essential Cookies</b> Type: Session Cookies Administered by: Us Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features.</li>
      <li><b>Cookies Policy/Notice Acceptance Cookies</b> Type: Persistent Cookies Administered by: Us Purpose: These cookies identify if users have accepted the use of cookies on the website.</li>
      <li><b>Functionality Cookies</b> Type: Persistent Cookies Administered by: Us Purpose: These cookies allow us to remember choices you make when you use the website.</li>
    </ul>
    
    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
    
    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    
    <ul>
      <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
      <li>To manage Your Account: to manage your registration as a user of the Service.</li>
      <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or any other contract with us through the Service.</li>
      <li>To contact You: To reach out to you by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
      <li>To manage Your requests: To attend and manage your requests to us.</li>
      <li>For business transfers: We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or any other sale or transfer of some or all of our assets.</li>
      <li>For other purposes: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, marketing, and your experience.</li>
    </ul>
    
    <p>We may share Your personal information in the following situations:</p>
    
    <ul>
      <li>With Service Providers: We may share your personal information with Service Providers to monitor and analyze the use of our Service, and to contact you.</li>
      <li>For business transfers: We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets!
        , financing, or acquisition of all or a portion of our business to another company.</li>
        
          <li>With Affiliates: We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.</li>
          <li>With business partners: We may share your information with our business partners to offer you certain products, services, or promotions.</li>
          <li>With other users: When you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
          <li>With your consent: We may disclose your personal information for any other purpose with your consent.</li>
        </ul>
        <h2>Retention of Your Personal Data</h2>
        <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>
        <h2>Transfer of Your Personal Data</h2>
        <p>Your information, including Personal Data, will be processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
        <h2>Deletion of Your Personal Data</h2>
        <p>You have the right to delete or request our assistance in deleting the personal data we have collected about you.</p>
        <p>Our service may allow you to delete certain information about yourself from within the service. You can update, amend, or delete your information at any time by logging into your account (if you have one) and accessing the account settings section to manage your personal information. You can also contact us to request access to, correction of, or deletion of any personal information you have provided to us.</p>
        <p>However, please note that we may need to retain certain information when we have a legal obligation or a lawful basis to do so.</p>
        <h2>Disclosure of Your Personal Data</h2>
        <h3>Business Transactions</h3>
        <p>If the Company is involved in a merger, acquisition, or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different privacy policy.</p>
        <h3>Law Enforcement</h3>
        <p>Under certain circumstances, the Company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g., a court or government agency).</p>
        <h3>Other Legal Requirements</h3>
        <p>The Company may disclose your personal data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
        <h2>Security of your personal data</h2>
        <p>Keeping your Personal Data secure is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>
    
        <h1>Children's privacy</h1>
        <p>Our Services are not directed to anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verifying parental consent, we will take steps to delete that information from our servers.</p>
            <p>If we need to rely on consent as the legal basis for processing your information and your country requires parental consent, we may require your parent's consent before collecting and using that information.</p>
    Links to other websites
    <p>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's website. We strongly recommend that you review the privacy policy of every website you visit.</p>
    <p>We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third party sites or services.</p>
    Changes to Privacy Policy
    <p>We may update our privacy policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will notify you via email and/or a prominent notice on our Service before changes become effective and update the "Last updated" date at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically to be aware of any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    contact us
    <p>If you have any questions about this privacy policy, you can contact us by:</p>
    <ul><li>Via email: <a link="aipoemgenerator@outlook.com">aipoemgenerator@outlook.com</a></li></ul>`,
  },
  fr: {
    header_title:"Générateur de poèmes - Créez un poème rimé avec l'IA gratuite",
    Description:"Un générateur de poèmes IA gratuit permettant de créer rapidement des poèmes rimés. Explorez notre générateur pour des poèmes personnalisés sur tout thème.",
    "poemai_title": "Générateur de poème",
    "poemai_input_title": "Générateur de poème",
    "poemai_input_subtitle": "Générer un poème sur...",
    "poemai_input_tips": "Première neige sur la montagne",
    "poemai_generate_btn": "Générer",
    "poemai_powered_by_gpt": "Propulsé par ChatGPT",
    "poemai_thinking_status": "Réflexion...",
    "poemai_network_err_toast": "Erreur réseau. Réessayez svp",
    "poemai_server_err_toast": "Erreur du serveur, veuillez réessayer",
    "poemai_generated_failed_toast": "Échec de la génération du poème, veuillez réessayer",
    "poemai_generated_poem": "Poème généré",
    "poemai_copy_btn": "Copier",
    "poemai_copy_success_toast": "Copié avec succès",
    "poemai_privacy": "Politique de confidentialité",
    poemai_title_generate:"Générer",
    privacyContent:`<h1>Politique de confidentialité</h1>
    <p>Dernière mise à jour : 5 janvier 2024<p>
    <p>Cette politique de confidentialité décrit nos politiques et procédures concernant la collecte, l'utilisation et la divulgation de vos informations lorsque vous utilisez le service et vous informe sur vos droits en matière de vie privée et comment la loi vous protège.<p>
    <p>Nous utilisons vos données personnelles pour fournir et améliorer le service. En utilisant le service, vous acceptez la collecte et l'utilisation des informations conformément à cette politique de confidentialité.<p>
    <h1>Interprétation et définitions</h1>
    <h2>Interprétation</h2>
    <p>Les mots dont la première lettre est en majuscule ont des significations définies dans les conditions suivantes. Ces définitions auront la même signification qu'elles apparaissent au singulier ou au pluriel.</p>
    <h2>Définitions</h2>
    <p>Aux fins de cette politique de confidentialité :<p>
    <ul><li><b>Compte</b> désigne un compte unique créé pour vous permettre d'accéder à notre service ou à des parties de notre service.</li>
    <li><b>Société</b> (désignée soit comme "la Société", "Nous", "Notre" ou "Nos" dans cet Accord) se réfère à Ai Poem Generator.</li>
    <li><b>Cookies</b> sont de petits fichiers placés sur votre ordinateur, appareil mobile ou tout autre appareil par un site web, contenant des détails de votre historique de navigation sur ce site web parmi ses nombreuses utilisations.</li>
    <li><b>Dispositif</b> désigne tout appareil pouvant accéder au service tel qu'un ordinateur, un téléphone portable ou une tablette numérique.</li>
    <li><b>Données personnelles</b> désigne toute information liée à une personne identifiée ou identifiable.</li>
    <li><b>Service</b> désigne le site web.</li>
    <li><b>Prestataire de services</b> désigne toute personne physique ou morale qui traite les données pour le compte de la société. Cela se réfère à des entreprises tierces ou des individus employés par la société pour faciliter le service, fournir le service pour le compte de la société, effectuer des services liés au service, ou aider la société à analyser comment le service est utilisé.</li>
    <li><b>Données d'utilisation</b> désigne les données collectées automatiquement, générées par l'utilisation du service ou provenant de l'infrastructure du service elle-même (par exemple, la durée d'une visite de page).</li>
    <li><b>Site web</b> désigne Ai Poem Generator, accessible depuis <a link="https://poemgenerator-ai.com/">https://poemgenerator-ai.com/</a></li>
    <li><b>Vous</b> désigne l'individu accédant ou utilisant le service, ou l'entreprise, ou autre entité juridique pour le compte de laquelle un tel individu accède ou utilise le service, le cas échéant.</li></ul>
    <h1>Collecte et utilisation de vos données personnelles</h1>
    <h2>Types de données collectées</h2>
    <h3>Données Personnelles</h3>
    <p>Lors de l'utilisation de notre service, nous pouvons vous demander de nous fournir certaines informations personnellement identifiables pouvant être utilisées pour vous contacter ou vous identifier. Les informations personnellement identifiables peuvent inclure, sans s'y limiter :</p>
    <ul><li>Adresse e-mail</li>
    <li>Données d'utilisation</li></ul>
    <h3>Données d'Utilisation</h3>
    <p>Les données d'utilisation sont collectées automatiquement lors de l'utilisation du service.</p>
    <p>L'utilisation des données peut inclure des informations telles que l'adresse de protocole Internet de votre appareil (par exemple, l'adresse IP), le type de navigateur, la version, les pages visitées sur notre service, l'heure et la date de la visite, le temps passé sur ces pages, les identifiants uniques de l'appareil et d'autres données diagnostiques.</p>
    <p>Lorsque vous accédez au service via un appareil mobile, nous pouvons collecter automatiquement certaines informations, y compris, mais sans s'y limiter, le type d'appareil mobile que vous utilisez, l'ID unique de votre appareil mobile, l'adresse IP de votre appareil mobile, votre système d'exploitation mobile, le type de navigateur internet mobile que vous utilisez, les identifiants uniques de l'appareil et d'autres données diagnostiques.</p>
    <p>Nous pouvons également collecter des informations envoyées par votre navigateur lorsque vous visitez notre service ou lorsque vous accédez au service via un appareil mobile.</p>
    <h3>Technologies de Suivi et Cookies</h3>
    <p>Nous utilisons des Cookies et des technologies de suivi similaires pour suivre les activités sur notre service et stocker certaines informations. Les technologies de suivi utilisées sont des balises, des étiquettes et des scripts pour collecter et suivre les informations et pour améliorer et analyser notre service. Les technologies que nous utilisons peuvent inclure :</p>
    <ul><li><b>Cookies ou Cookies de Navigateur.</b> Un cookie est un petit fichier placé sur votre appareil. Vous pouvez configurer votre navigateur pour refuser tous les cookies ou pour indiquer quand un cookie est envoyé. Cependant, si vous n'acceptez pas les cookies, vous pourriez ne pas être en mesure d'utiliser certaines parties de notre service. Sauf si vous avez ajusté la configuration de votre navigateur pour refuser les cookies, notre service peut utiliser des cookies.</li>
    <li><b>Balises Web.</b> Certaines sections de notre service et nos e-mails peuvent contenir de petits fichiers électroniques connus sous le nom de balises web (également appelés gifs transparents, balises pixel et gifs monopixel) qui permettent à l'entreprise, par exemple, de compter les utilisateurs qui ont visité ces pages ou ouvert un e-mail et d'autres statistiques de sites web connexes (telles que l'enregistrement de la popularité d'une certaine section et la vérification de l'intégrité du système et du serveur).</li></ul>
    <p>Les cookies peuvent être "Persistants" ou "De Session". Les cookies persistants restent sur votre ordinateur personnel ou votre appareil mobile lorsque vous êtes hors ligne, tandis que les cookies de session sont supprimés dès que vous fermez votre navigateur web.</p>
    <p>Nous utilisons à la fois des cookies de session et des cookies persistants pour les objectifs décrits ci-dessous :</p>
    <ul><li><b>Cookies Nécessaires/Essentiels</b> Type : Cookies de Session Administrés par : Nous Objectif : Ces cookies sont essentiels pour vous fournir les services disponibles via le site web et pour vous permettre d'utiliser certaines de ses fonctionnalités. Ils aident à authentifier les utilisateurs et à prévenir l'utilisation frauduleuse des comptes utilisateurs. Sans ces cookies, les services que vous avez demandés ne peuvent être fournis, et nous utilisons ces cookies uniquement pour vous fournir ces services.</li>
    <li><b>Cookies de Politique/Notice d'Acceptation</b> Type : Cookies Persistants Administrés par : Nous Objectif : Ces cookies identifient si les utilisateurs ont accepté l'utilisation de cookies sur le site web.</li>
    <li><b>Cookies de Fonctionnalité</b> Type : Cookies Persistants Administrés par : Nous Objectif : Ces cookies nous permettent de nous souvenir des choix que vous faites lorsque vous utilisez le site web, tels que se souvenir de vos détails de connexion ou de votre préférence linguistique. L'objectif de ces cookies est de vous fournir une expérience plus personnelle et d'éviter que vous ayez à saisir à nouveau vos préférences chaque fois que vous utilisez le site web.</li></ul>
    <p>Pour plus d'informations sur les cookies que nous utilisons et vos choix concernant les cookies, veuillez visiter notre Politique de Cookies ou la section Cookies de notre Politique de Confidentialité.</p>
    <h2>Utilisation de vos données personnelles</h2>
    <p>La société peut utiliser les données personnelles aux fins suivantes :</p>
    <ul><li><b>Pour fournir et maintenir notre service,</b> y compris pour surveiller l'utilisation de notre service.</li>
    <li><b>Pour gérer votre compte</b> : gérer votre inscription en tant qu'utilisateur du service. Les données personnelles que vous fournissez peuvent vous donner accès à différentes fonctionnalités du service disponibles en tant qu'utilisateur enregistré.</li>
    <li><b>Pour la performance d'un contrat</b> : le développement, la conformité et l'exécution du contrat d'achat pour les produits, articles ou services que vous avez achetés ou tout autre contrat avec nous via le service.</li>
    <li><b>Pour vous contacter</b> : vous joindre par e-mail, appels téléphoniques, SMS ou autres formes équivalentes de communication électronique, telles que les notifications push d'applications mobiles concernant les mises à jour ou les communications informatives liées aux fonctionnalités, produits ou services contractés, y compris les mises à jour de sécurité nécessaires.</li>
    <li><b>Pour gérer vos demandes</b> : répondre et gérer vos demandes à nous.</li>
    <li><b>Pour les transferts d'entreprise</b> : Nous pouvons utiliser vos informations pour évaluer ou effectuer une fusion, une cession, une restructuration, une réorganisation, une dissolution ou toute autre vente ou transfert de tout ou partie de nos actifs, que ce soit dans le cadre d'une exploitation continue ou dans le cadre d'une faillite, liquidation ou procédure similaire, dans laquelle les données personnelles détenues par nous concernant nos utilisateurs de services font partie des actifs transférés.</li>
    <li><b>Pour d'autres objectifs</b> : Nous pouvons utiliser vos informations à d'autres fins, telles que l'analyse de données, l'identification des tendances d'utilisation, la détermination de l'efficacité de nos campagnes promotionnelles, et pour évaluer et améliorer notre service, nos produits, notre marketing et votre expérience.</li></ul>
    <p>Nous pouvons partager vos informations personnelles dans les situations suivantes :</p>
    <ul><li><b>Avec des prestataires de services</b> : Nous pouvons partager vos informations personnelles avec des prestataires de services pour surveiller et analyser l'utilisation de notre service, et pour vous contacter.</li>
    <li><b>Pour les transferts d'entreprise</b> : Nous pouvons partager ou transférer vos informations personnelles en relation avec, ou lors des négociations de, toute fusion, vente d'actifs de l'entreprise, financement ou acquisition de tout ou partie de notre entreprise par une autre entreprise.</li>
    <li><b>Avec des affiliés</b> : Nous pouvons partager vos informations avec nos affiliés, auquel cas nous exigerons que ces affiliés respectent cette politique de confidentialité. Les affiliés incluent notre société mère et toutes autres filiales, partenaires de joint-venture ou autres entreprises que nous contrôlons ou qui sont sous contrôle commun avec nous.</li>
    <li><b>Avec des partenaires commerciaux : Nous pouvons partager vos informations avec nos partenaires commerciaux pour vous proposer certains produits, services ou promotions.</li>
    <li><b>Avec d'autres utilisateurs</b> : Lorsque vous partagez des informations personnelles ou interagissez autrement dans les zones publiques avec d'autres utilisateurs, ces informations peuvent être vues par tous les utilisateurs et peuvent être distribuées publiquement à l'extérieur.</li>
    <li><b>Avec votre consentement</b> : Nous pouvons divulguer vos informations personnelles à toute autre fin avec votre consentement.</li></ul>
    <h2>Conservation de vos données personnelles</h2>
    <p>La société conservera vos données personnelles uniquement pendant la durée nécessaire aux fins énoncées dans cette politique de confidentialité. Nous conserverons et utiliserons vos données personnelles dans la mesure nécessaire pour respecter nos obligations légales (par exemple, si nous sommes tenus de conserver vos données pour nous conformer aux lois applicables), résoudre les litiges et faire respecter nos accords et politiques juridiques.</p>
    <p>La société conservera également les données d'utilisation à des fins d'analyse interne. Les données d'utilisation sont généralement conservées pendant une période plus courte, sauf lorsque ces données sont utilisées pour renforcer la sécurité ou améliorer la fonctionnalité de notre service, ou lorsque nous sommes légalement tenus de conserver ces données pendant des périodes plus longues.</p>
    <h2>Transfert de vos données personnelles</h2>
    <p>Vos informations, y compris les données personnelles, seront traitées dans les bureaux opérationnels de la société et dans tous les autres lieux où les parties impliquées dans le traitement sont situées. Cela signifie que ces informations peuvent être transférées et maintenues sur des ordinateurs situés en dehors de votre état, province, pays ou autre juridiction gouvernementale où les lois sur la protection des données peuvent différer de celles de votre juridiction.</p>
    <p>Votre consentement à cette politique de confidentialité, suivi de la soumission de ces informations, représente votre accord pour ce transfert. La société prendra toutes les mesures raisonnablement nécessaires pour garantir que vos données sont traitées de manière sécurisée et conformément à cette politique de confidentialité et aucun transfert de vos données personnelles n'aura lieu vers une organisation ou un pays à moins qu'il n'existe des contrôles adéquats, y compris la sécurité de vos données et autres informations personnelles.</p>
    <h2>Suppression de vos données personnelles</h2>
    <p>Vous avez le droit de supprimer ou de demander notre aide pour supprimer les données personnelles que nous avons collectées à votre sujet.</p>
    <p>Notre service peut vous permettre de supprimer certaines informations vous concernant depuis le service.</p>
    <p>Vous pouvez mettre à jour, modifier ou supprimer vos informations à tout moment en vous connectant à votre compte (si vous en avez un) et en accédant à la section des paramètres du compte pour gérer vos informations personnelles. Vous pouvez également nous contacter pour demander l'accès, la correction ou la suppression de toute information personnelle que vous nous avez fournie.</p>
    <p>Cependant, veuillez noter que nous pouvons être tenus de conserver certaines informations lorsque nous avons une obligation légale ou une base légale pour le faire.</p>
    <h2>Divulgation de vos données personnelles</h2>
    <h3>Transactions commerciales</h3>
    <p>Si la société est impliquée dans une fusion, une acquisition ou une vente d'actifs, vos données personnelles peuvent être transférées. Nous vous fournirons un avis avant que vos données personnelles soient transférées et deviennent soumises à une politique de confidentialité différente.</p>
    <h3>Application de la loi</h3>
    <p>Dans certaines circonstances, la société peut être tenue de divulguer vos données personnelles si la loi l'exige ou en réponse à des demandes valides des autorités publiques (par exemple, un tribunal ou une agence gouvernementale).</p>
    <h3>Autres exigences légales</h3>
    <p>La société peut divulguer vos données personnelles en croyant de bonne foi que cette action est nécessaire pour :</p>
    <ul><li>Se conformer à une obligation légale</li>
    <li>Protéger et défendre les droits ou la propriété de la société</li>
    <li>Prévenir ou enquêter sur un éventuel méfait en lien avec le service</li>
    <li>Protéger la sécurité personnelle des utilisateurs du service ou du public</li>
    <li>Se protéger contre la responsabilité légale</li></ul>
    <h2>Sécurité de vos données personnelles</h2>
    <p>Il est important pour nous de sécuriser vos données personnelles, mais rappelez-vous qu'aucune méthode de transmission sur Internet ou méthode de stockage électronique n'est sécurisée à 100%. Bien que nous nous efforcions d'utiliser des moyens commercialement acceptables pour protéger vos données personnelles, nous ne pouvons pas garantir leur sécurité absolue.</p>
    <h1>Confidentialité des enfants</h1>
    <p>Nos services ne sont pas destinés aux personnes âgées de moins de 13 ans. Nous ne collectons pas sciemment des informations personnellement identifiables de personnes de moins de 13 ans. Si vous êtes un parent ou un tuteur et que vous êtes conscient que votre enfant nous a fourni des données personnelles, veuillez nous contacter. Si nous prenons conscience que nous avons collecté des données personnelles de toute personne de moins de 13 ans sans vérification du consentement parental, nous prendrons des mesures pour supprimer ces informations de nos serveurs.</p>
    <p>Si nous devons nous appuyer sur le consentement comme base légale pour le traitement de vos informations et que votre pays exige le consentement parental, nous pouvons exiger le consentement de vos parents avant de collecter et d'utiliser ces informations.</p>
    <h1>Liens vers d'autres sites web</h1>
    <p>Notre service peut contenir des liens vers d'autres sites web qui ne sont pas exploités par nous. Si vous cliquez sur un lien tiers, vous serez dirigé vers le site web de ce tiers. Nous vous recommandons fortement de consulter la politique de confidentialité de chaque site web que vous visitez.</p>
    <p>Nous n'avons aucun contrôle et n'assumons aucune responsabilité quant au contenu, aux politiques de confidentialité ou aux pratiques de tout site ou service tiers.</p>
    <h1>Modifications de la politique de confidentialité</h1>
    <p>Nous pouvons mettre à jour notre politique de confidentialité de temps à autre. Nous vous informerons de tout changement en publiant la nouvelle politique de confidentialité sur cette page.</p>
    <p>Nous vous informerons par e-mail et/ou un avis bien visible sur notre service avant que les changements deviennent effectifs et mettrons à jour la date de "Dernière mise à jour" en haut de cette politique de confidentialité.</p>
    <p>Vous êtes conseillé de revoir périodiquement cette politique de confidentialité pour être au courant de tout changement. Les modifications de cette politique de confidentialité sont effectives lorsqu'elles sont publiées sur cette page.</p>
    <h1>Contactez-nous</h1>
    <p>Si vous avez des questions concernant cette politique de confidentialité, vous pouvez nous contacter par :</p>
    <ul><li>Via e-mail : <a link="aipoemgenerator@outlook.com">aipoemgenerator@outlook.com</a></li></ul>`,
    
    poemai_fv_theme:"De quoi parle le poème?",
  },
  ru: {
    header_title:"Генератор стихов - создайте рифму с бесплатным AI",
    Description:"Бесплатный генератор стихов на ИИ: создание рифмованных стихов в секунды. Откройте наш генератор и напишите красивое стихотворение.",
    "poemai_title": "Генератор Стихов",
    "poemai_input_title": "Генератор Стихов",
    "poemai_input_subtitle": "Сгенерировать стих о...",
    "poemai_input_tips": "Ветер в поле звенит",
    "poemai_generate_btn": "Генерировать",
    "poemai_powered_by_gpt": "На платформе ChatGPT",
    "poemai_thinking_status": "Думаю...",
    "poemai_network_err_toast": "Ошибка сети. Попробуйте еще раз",
    "poemai_server_err_toast": "Ошибка сервера, попробуйте еще раз",
    "poemai_generated_failed_toast": "Не удалось сгенерировать стих, попробуйте еще раз",
    "poemai_generated_poem": "Сгенерированный стих",
    "poemai_copy_btn": "Копировать",
    "poemai_copy_success_toast": "Успешно скопировано",
    "poemai_privacy": "Политика конфиденциальности",
    poemai_title_generate:"Генерировать",
    poemai_fv_theme:"О чем этот стих?",
    privacyContent:`<h1>Политика конфиденциальности</h1>
    <p>Последнее обновление: 5 января 2024 года<p>
    <p>Настоящая Политика конфиденциальности описывает наши политики и процедуры по сбору, использованию и раскрытию вашей информации, когда вы используете Сервис, и информирует вас о ваших правах на конфиденциальность и о том, как закон защищает вас.<p>
    <p>Мы используем ваши персональные данные для предоставления и улучшения Сервиса. Используя Сервис, вы соглашаетесь на сбор и использование информации в соответствии с настоящей Политикой конфиденциальности.<p>
    <h1>Толкование и Определения</h1>
    <h2>Толкование</h2>
    <p>Слова с заглавной буквы имеют значения, определенные в следующих условиях. Эти определения будут иметь одно и то же значение, независимо от того, появляются ли они в единственном или множественном числе.</p>
    <h2>Определения</h2>
    <p>В целях настоящей Политики конфиденциальности:<p>
    <ul><li><b>Аккаунт</b> относится к уникальному аккаунту, созданному для вас для доступа к нашему сервису или его частям.</li>
    <li><b>Компания</b> (указана как "Компания", "Мы", "Нас" или "Наши" в данном Соглашении) относится к Ai Poem Generator.</li>
    <li><b>Cookies</b> (Куки) - это маленькие файлы, размещаемые на вашем компьютере, мобильном устройстве или любом другом устройстве веб-сайтом, содержащие детали вашей истории просмотра на этом веб-сайте среди его многих применений.</li>
    <li><b>Устройство</b> означает любое устройство, которое может получить доступ к Сервису, такое как компьютер, мобильный телефон или цифровой планшет.</li>
    <li><b>Персональные данные</b> любая информация, связанная с идентифицированным или идентифицируемым индивидуумом.</li>
    <li><b>Сервис</b> относится к Веб-сайту.</li>
    <li><b>Провайдер услуг</b> означает любое физическое или юридическое лицо, которое обрабатывает данные от имени Компании. Это относится к сторонним компаниям или лицам, нанятым Компанией для облегчения работы Сервиса, предоставления Сервиса от имени Компании, выполнения услуг, связанных с Сервисом, или помощи Компании в анализе использования Сервиса.</li>
    <li><b>Данные использования</b> относятся к данным, собираемым автоматически, либо сгенерированным в результате использования Сервиса, либо из самой инфраструктуры Сервиса (например, продолжительность посещения страницы).</li>
    <li><b>Веб-сайт</b> относится к Ai Poem Generator, доступному с  <a link="https://poemgenerator-ai.com/">https://poemgenerator-ai.com/</a></li>
    <li><b>Вы</b> означаете лицо, получающее доступ к Сервису или использующее его, или компанию, или другую юридическую сущность, от имени которой такое лицо получает доступ к Сервису или использует его, в зависимости от обстоятельств.</li></ul>
    <h1>Сбор и использование ваших личных данных</h1>
    <h2>Типы собираемых данных</h2>
    <h3>Личные данные</h3>
    <p>При использовании нашего сервиса мы можем попросить вас предоставить нам определенную информацию, которая позволяет установить вашу личность и может быть использована для связи с вами или вашей идентификации. Информация, позволяющая установить личность, может включать, но не ограничивается:</p>
    <ul>
      <li>Электронный адрес</li>
      <li>Данные об использовании</li>
    </ul>
    <h3>Данные об использовании</h3>
    <p>Данные об использовании собираются автоматически при использовании сервиса.</p>
    <p>Использование данных может включать информацию, такую как адрес интернет-протокола вашего устройства (например, IP-адрес), тип браузера, версию, страницы, посещенные в нашем сервисе, время и дата посещения, время, проведенное на этих страницах, уникальные идентификаторы устройства и другие диагностические данные.</p>
    <p>Когда вы получаете доступ к сервису через мобильное устройство, мы можем автоматически собирать определенную информацию, включая, но не ограничиваясь, тип используемого вами мобильного устройства, уникальный ID вашего мобильного устройства, IP-адрес вашего мобильного устройства, вашу мобильную операционную систему, тип используемого вами мобильного интернет-браузера, уникальные идентификаторы устройства и другие диагностические данные.</p>
    <p>Мы также можем собирать информацию, отправленную вашим браузером, когда вы посещаете наш сервис или когда вы получаете доступ к сервису через мобильное устройство.</p>
    <h3>Технологии отслеживания и Cookies</h3>
    <p>Мы используем Cookies и похожие технологии отслеживания для отслеживания активности на нашем сервисе и хранения определенной информации. Используемые технологии отслеживания включают маяки, теги и скрипты для сбора и отслеживания информации, а также для улучшения и анализа нашего сервиса. Технологии, которые мы используем, могут включать:</p>
    <ul>
      <li><b>Cookies или браузерные Cookies.</b> Cookie — это небольшой файл, размещаемый на вашем устройстве. Вы можете настроить свой браузер на отказ от всех cookies или указать, когда отправляется cookie. Однако, если вы не принимаете cookies, вы можете быть не в состоянии использовать некоторые части нашего сервиса. Если вы не настроили свой браузер на отказ от cookies, наш сервис может использовать cookies.</li>
      <li><b>Веб-маяки.</b> Некоторые разделы нашего сервиса и наши электронные письма могут содержать небольшие электронные файлы, известные как веб-маяки (также называемые чистыми gifs, пиксельными тегами и gifs моно-пикселя), которые позволяют компании, например, подсчитать пользователей, посетивших эти страницы или открывших электронное письмо, и другую связанную статистику веб-сайтов (например, записывать популярность определенного раздела и проверять целостность системы и сервера).</li>
    </ul>
    <p>Cookies могут быть "Постоянными" или "Сессионными". Постоянные cookies остаются на вашем персональном компьютере или мобильном устройстве, когда вы выходите в оффлайн, в то время как сессионные cookies удаляются, как только вы закрываете ваш веб-браузер.</p>
    <p>Мы используем как сессионные, так и постоянные cookies для целей, изложенных ниже:</p>
    <ul>
      <li><b>Необходимые/Основные Cookies</b> Тип: Сессионные Cookies Управляются: Нами Цель: Эти cookies необходимы для предоставления вам услуг, доступных через веб-сайт, и для использования некоторых его функций. Они помогают аутентифицировать пользователей и предотвращать мошенническое использование учетных записей пользователей. Без этих cookies услуги, которые вы запросили, не могут быть предоставлены, и мы используем эти cookies только для предоставления вам этих услуг.</li>
      <li><b>Cookies Политики/Уведомления о Принятии</b> Тип: Постоянные Cookies Управляются: Нами Цель: Эти cookies определяют, приняли ли пользователи использование cookies на веб-сайте.</li>
      <li><b>Функциональные Cookies</b> Тип: Постоянные Cookies Управляются: Нами Цель: Эти cookies позволяют нам запоминать выбор, который вы делаете, когда используете веб-сайт, например, запоминая ваши данные для входа или предпочтения языка. Цель этих cookies - предоставить вам более персональный опыт и избежать необходимости каждый раз вводить ваши предпочтения при использовании веб-сайта.</li>
    </ul>
    <p>Для получения дополнительной информации о cookies, которые мы используем, и о ваших выборах, касающихся cookies, пожалуйста, посетите нашу Политику использования cookies или раздел Cookies нашей Политики конфиденциальности.</p>
    
    <h2>Использование ваших личных данных</h2>
    <p>Компания может использовать личные данные для следующих целей:</p>
    
    <ul>
      <li><b>Для предоставления и поддержания нашего сервиса,</b> включая мониторинг использования нашего сервиса.</li>
      <li><b>Для управления вашим аккаунтом:</b> управлять вашей регистрацией как пользователя сервиса. Предоставленные вами личные данные могут предоставить вам доступ к различным функциям сервиса, доступным вам как зарегистрированному пользователю.</li>
      <li><b>Для исполнения контракта:</b> разработка, соблюдение и выполнение контракта на покупку продуктов, товаров или услуг, которые вы приобрели, или любого другого контракта с нами через сервис.</li>
      <li><b>Для связи с вами:</b> связаться с вами по электронной почте, телефонным звонкам, СМС или другим эквивалентным формам электронной коммуникации, таким как push-уведомления мобильного приложения, касающиеся обновлений или информационных сообщений, связанных с функциональностью, продуктами или заключенными услугами, включая необходимые обновления безопасности.</li>
      <li><b>Для управления вашими запросами:</b> обрабатывать и управлять вашими запросами к нам.</li>
      <li><b>Для бизнес-передач:</b> Мы можем использовать ваши данные для оценки или проведения слияния, продажи активов компании, финансирования или приобретения всей или части нашего бизнеса другой компанией, будь то как действующее предприятие или как часть процесса банкротства, ликвидации или аналогичной процедуры, в которой личные данные, которые мы держим о пользователях нашего сервиса, являются одним из передаваемых активов.</li>
      <li><b>Для других целей:</b> Мы можем использовать ваши данные для других целей, таких как анализ данных, выявление тенденций использования, определение эффективности наших рекламных кампаний и для оценки и улучшения нашего сервиса, продуктов, маркетинга и вашего опыта.</li>
    </ul>
    
    <p>Мы можем делиться вашей персональной информацией в следующих ситуациях:</p>
    
    <ul>
      <li><b>С поставщиками услуг:</b> Мы можем делиться вашей персональной информацией с поставщиками услуг для мониторинга и анализа использования нашего сервиса и для связи с вами.</li>
      <li><b>Для бизнес-передач:</b> Мы можем делиться или передавать вашу персональную информацию в связи с или во время переговоров о любом слиянии, продаже активов компании, финансировании или приобретении всей или части нашего бизнеса другой компанией.</li>
      <li><b>С аффилированными лицами:</b> Мы можем делиться вашей информацией с нашими аффилированными лицами, в таком случае мы потребуем, чтобы эти аффилированные лица соблюдали настоящую политику конфиденциальности. Аффилированные лица включают нашу материнскую компанию и любые другие дочерние компании, партнеры по совместному предприятию или другие компании, которыми мы управляем или которые находятся под общим управлением с нами.</li>
      <li><b>С бизнес-партнерами:</b> Мы можем делиться вашей информацией с нашими бизнес-партнерами для предложения вам определенных продуктов, услуг или акций.</li>
      <li><b>С другими пользователями:</b> Когда вы делитесь личной информацией или иным образом взаимодействуете в общественных местах с другими пользователями, такая информация может быть видна всем пользователям и может быть распространена за пределами публично.</li>
      <li><b>С вашего согласия:</b> Мы можем раскрывать вашу персональную информацию для любых других целей с вашего согласия.</li>
    </ul>
    <h2>Сохранение Ваших Личных Данных</h2>
    <p>Компания будет сохранять Ваши личные данные только столько времени, сколько это необходимо для целей, изложенных в настоящей Политике конфиденциальности. Мы будем сохранять и использовать Ваши личные данные в той мере, в которой это необходимо для выполнения наших юридических обязательств (например, если нам требуется сохранить Ваши данные для соблюдения применимых законов), разрешения споров и выполнения наших юридических соглашений и политик.</p>
    <p>Компания также будет сохранять Данные об использовании для целей внутреннего анализа. Данные об использовании обычно сохраняются в течение более короткого периода, за исключением случаев, когда эти данные используются для укрепления безопасности или улучшения функциональности нашего Сервиса, или когда мы юридически обязаны сохранять эти данные на более длительные периоды.</p>
    
    <h2>Передача Ваших Личных Данных</h2>
    <p>Ваша информация, включая Личные Данные, будет обрабатываться в операционных офисах Компании и в любых других местах, где находятся стороны, участвующие в обработке. Это означает, что эта информация может быть передана и сохранена на компьютерах, расположенных за пределами вашего штата, провинции, страны или другой государственной юрисдикции, где законы о защите данных могут отличаться от тех, что действуют в вашей юрисдикции.</p>
    <p>Ваше согласие с настоящей Политикой конфиденциальности, за которым следует ваше предоставление такой информации, означает ваше согласие на такую передачу. Компания предпримет все разумно необходимые шаги для того, чтобы обеспечить безопасную обработку ваших данных в соответствии с настоящей Политикой конфиденциальности и не допустит передачи Ваших Личных Данных организации или стране, если там не будут налажены адекватные контроли, включая защиту ваших данных и другой личной информации.</p>
    
    <h2>Удаление Ваших Личных Данных</h2>
    <p>У вас есть право удалить или запросить нашу помощь в удалении личных данных, которые мы собрали о вас.</p>
    <p>Наш сервис может позволять вам удалять определенную информацию о себе из сервиса.</p>
    <p>Вы можете в любое время обновить, изменить или удалить свою информацию, войдя в свой аккаунт (если он у вас есть) и получив доступ к разделу настроек аккаунта для управления вашей личной информацией. Вы также можете связаться с нами, чтобы запросить доступ, исправление или удаление любой личной информации, которую вы нам предоставили.</p>
    <p>Однако, обратите внимание, что нам может потребоваться сохранить определенную информацию, когда у нас есть юридическое обязательство или законное основание для этого.</p>
    
    <h2>Раскрытие Ваших Личных Данных</h2>
    <h3>Деловые Сделки</h3>
    <p>Если Компания участвует в слиянии, приобретении или продаже активов, ваши личные данные могут быть переданы. Мы предоставим уведомление до передачи ваших личных данных и до того, как они станут подпадать под действие другой политики конфиденциальности.</p>
    <h3>Правоохранительные Органы</h3>
    <p>В определенных обстоятельствах Компания может быть обязана раскрыть ваши личные данные, если это требуется по закону или в ответ на действительные запросы публичных органов (например, суда или государственного агентства).</p>
    <h3>Другие Юридические Требования</h3>
    <p>Компания может раскрыть ваши личные данные в добросовестной уверенности, что такое действие необходимо для:</p>
    <ul>
      <li>Соблюдения юридического обязательства</li>
      <li>Защиты и обороны прав или собственности Компании</li>
      <li>Предотвращения или расследования возможного неправомерного действия в связи с Сервисом</li>
      <li>Защиты личной безопасности пользователей Сервиса или общественности</li>
      <li>Защиты от юридической ответственности</li>
    </ul>
    <h2>Безопасность ваших личных данных</h2>
    <p>Для нас важно обеспечивать безопасность ваших личных данных, но помните, что ни один метод передачи через Интернет, ни метод электронного хранения не являются 100% безопасными. Хотя мы стремимся использовать коммерчески приемлемые средства для защиты ваших личных данных, мы не можем гарантировать их абсолютную безопасность.</p>
    
    <h1>Конфиденциальность детей</h1>
    <p>Наши услуги не предназначены для лиц младше 13 лет. Мы не собираем сознательно личную информацию от лиц младше 13 лет. Если вы родитель или опекун и вы знаете, что ваш ребенок предоставил нам Личные Данные, пожалуйста, свяжитесь с нами. Если мы узнаем, что собрали личные данные от лица младше 13 лет без проверки согласия родителей, мы предпримем шаги для удаления этой информации с наших серверов.</p>
    
    <p>Если нам необходимо полагаться на согласие в качестве юридической основы для обработки вашей информации и ваша страна требует согласия родителей, мы можем требовать согласия ваших родителей перед сбором и использованием этой информации.</p>
    
    <h1>Ссылки на другие сайты</h1>
    <p>Наш сервис может содержать ссылки на другие сайты, которые не управляются нами. Если вы нажмете на ссылку третьей стороны, вы будете направлены на веб-сайт этой третьей стороны. Мы настоятельно рекомендуем вам ознакомиться с политикой конфиденциальности каждого посещаемого вами сайта.</p>
    
    <p>Мы не контролируем и не несем ответственности за содержание, политики конфиденциальности или практики любых сайтов или услуг третьих сторон.</p>
    
    <h1>Изменения в политике конфиденциальности</h1>
    <p>Мы можем время от времени обновлять нашу политику конфиденциальности. Мы уведомим вас о любых изменениях, разместив новую политику конфиденциальности на этой странице.</p>
    
    <p>Мы уведомим вас по электронной почте и/или заметным уведомлением на нашем сервисе перед вступлением изменений в силу и обновим дату "Последнего обновления" в верхней части этой политики конфиденциальности.</p>
    
    <p>Вам рекомендуется периодически просматривать эту политику конфиденциальности, чтобы быть в курсе любых изменений. Изменения в этой политике конфиденциальности вступают в силу, когда они опубликованы на этой странице.</p>
    
    <h1>Свяжитесь с нами</h1>
    <p>Если у вас есть вопросы о этой политике конфиденциальности, вы можете связаться с нами:</p>
    <ul><li>По электронной почте: <a link="aipoemgenerator@outlook.com">aipoemgenerator@outlook.com</a></li></ul>
    `
  },
  de: {
    header_title:"Gedichten Generator - Kostenloses KI-Magie-Tool für Reimgedichte",
    Description:"Kostenloser AI-Gedichten Generator: Erstellen Sie Reimgedichte in Sekundenschnelle. Entdecken Sie unseren Generator und erstellen Sie Reimgedichte zu jedem Thema.",
    "poemai_title": "Gedichten Generator",
    "poemai_input_title": "Gedichten Generator",
    "poemai_input_subtitle": "Generiere ein Gedicht über...",
    "poemai_input_tips": "Herbstwind in den alten Gassen",
    "poemai_generate_btn": "Generieren",
    "poemai_powered_by_gpt": "Angetrieben von ChatGPT",
    "poemai_thinking_status": "Denken...",
    "poemai_network_err_toast": "Netzwerkfehler. Bitte versuchen Sie es erneut",
    "poemai_server_err_toast": "Serverfehler, bitte versuchen Sie es erneut",
    "poemai_generated_failed_toast": "Gedicht konnte nicht generiert werden, bitte versuchen Sie es erneut",
    "poemai_generated_poem": "Generiertes Gedicht",
    "poemai_copy_btn": "Kopieren",
    "poemai_copy_success_toast": "Erfolgreich kopiert",
    "poemai_privacy": "Datenschutzrichtlinie",
    poemai_title_generate:"Generieren",
    poemai_fv_theme:"Worum geht es in dem Gedicht?",
    privacyContent:`<h1>Datenschutzrichtlinie</h1>
    <p>Letzte Aktualisierung: 5. Januar 2024</p>
    <p>Diese Datenschutzrichtlinie umreißt unsere Richtlinien und Verfahren zur Sammlung, Nutzung und Offenlegung Ihrer Informationen, wenn Sie den Dienst nutzen, und informiert Sie über Ihre Datenschutzrechte und wie das Gesetz Sie schützt.</p>
    <p>Wir nutzen Ihre persönlichen Daten, um den Service bereitzustellen und zu verbessern. Durch die Nutzung des Dienstes stimmen Sie der Sammlung und Nutzung von Informationen gemäß dieser Datenschutzrichtlinie zu.</p>
    <h1>Interpretation und Definitionen</h1>
    <h2>Interpretation</h2>
    <p>Wörter, deren Anfangsbuchstaben großgeschrieben sind, haben unter den folgenden Bedingungen definierte Bedeutungen. Diese Definitionen haben die gleiche Bedeutung, unabhängig davon, ob sie im Singular oder Plural erscheinen.</p>
    <h2>Definitionen
    <p>Zu den Zwecken dieser Datenschutzrichtlinie:</p>
    <ul><li><b>"Konto"</b>bezieht sich auf ein einzigartiges Konto, das für Sie erstellt wurde, um auf unseren Dienst oder Teile unseres Dienstes zuzugreifen.</li>
    <li><b>Unternehmen</b> (bezeichnet als "das Unternehmen", "Wir", "Uns" oder "Unser" in diesem Vertrag) bezieht sich auf Ai Poem Generator.</li>
    <li><b>Cookies</b> sind kleine Dateien, die von einer Website auf Ihrem Computer, Mobilgerät oder einem anderen Gerät platziert werden und Einzelheiten zu Ihrem Browserverlauf auf dieser Website unter vielen Verwendungen enthalten.</li>
    <li><b>Gerät</b> bedeutet jedes Gerät, das auf den Dienst zugreifen kann, wie z. B. ein Computer, ein Handy oder ein digitales Tablet.</li>
    <li><b>Personenbezogene Daten</b>sind alle Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen.</li>
    <li><b>Dienst</b> bezieht sich auf die Website.</li>
    <li><b>Dienstanbieter</b> bedeutet jede natürliche oder juristische Person, die Daten im Auftrag des Unternehmens verarbeitet. Dies bezieht sich auf Drittunternehmen oder Einzelpersonen, die vom Unternehmen beschäftigt werden, um den Dienst zu erleichtern, den Dienst im Namen des Unternehmens bereitzustellen, Dienstleistungen im Zusammenhang mit dem Dienst zu erbringen oder das Unternehmen bei der Analyse der Nutzung des Dienstes zu unterstützen.</li>
    <li><b>Nutzungsdaten</b> bezieht sich auf Daten, die automatisch gesammelt werden, entweder generiert durch die Nutzung des Dienstes oder aus der Infrastruktur des Dienstes selbst (zum Beispiel die Dauer eines Seitenbesuchs).</li>
    <li><b>Website</b> bezieht sich auf Ai Poem Generator, zugänglich von <a link="https://poemgenerator-ai.com/">https://poemgenerator-ai.com/</a></li>
    <li><b>Sie</b> bezieht sich auf die Einzelperson, die den Dienst nutzt oder darauf zugreift, oder das Unternehmen oder eine andere juristische Entität, in deren Auftrag die betreffende Person den Dienst nutzt oder darauf zugreift.</li></ul>
    <h1>Erfassung und Verwendung Ihrer persönlichen Daten</h1>
    <h2>Arten von erfassten Daten</h2>
    <h3>Persönliche Daten</h3>
    <p>Bei der Nutzung unseres Dienstes können wir Sie bitten, uns bestimmte persönlich identifizierbare Informationen zur Verfügung zu stellen, die zur Kontaktaufnahme oder Identifikation verwendet werden können. Persönlich identifizierbare Informationen können beinhalten, sind aber nicht beschränkt auf:</p>
    <ul><li>E-Mail-Adresse</li>
    <li>Nutzungsdaten</li></ul>
    <h3>Nutzungsdaten</h3>
    <p>Nutzungsdaten werden automatisch gesammelt, wenn Sie den Dienst nutzen.</p>
    <p>Die Verwendung der Daten kann Informationen wie die Internetprotokolladresse Ihres Geräts (z.B. IP-Adresse), Browsertyp, Version, besuchte Seiten unseres Dienstes, Besuchszeit und -datum, auf diesen Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere diagnostische Daten umfassen.</p>
    <p>Wenn Sie auf den Dienst über ein mobiles Gerät zugreifen, können wir automatisch bestimmte Informationen sammeln, einschließlich, aber nicht beschränkt auf, den Typ des mobilen Geräts, das Sie verwenden, die eindeutige ID Ihres mobilen Geräts, die IP-Adresse Ihres mobilen Geräts, Ihr mobiles Betriebssystem, den Typ des mobilen Internetbrowsers, den Sie verwenden, eindeutige Gerätekennungen und andere diagnostische Daten.</p>
    <p>Wir können auch Informationen sammeln, die von Ihrem Browser gesendet werden, wenn Sie unseren Dienst besuchen oder darauf über ein mobiles Gerät zugreifen.</p>
    <h3>Tracking-Technologien und Cookies</h3>
    <p>Wir verwenden Cookies und ähnliche Tracking-Technologien, um Aktivitäten auf unserem Dienst zu verfolgen und bestimmte Informationen zu speichern. Die eingesetzten Tracking-Technologien sind Beacons, Tags und Skripte, um Informationen zu sammeln und zu verfolgen sowie unseren Dienst zu verbessern und zu analysieren. Die von uns verwendeten Technologien können umfassen:</p>
    <ul><li><b>Cookies oder Browser-Cookies.</b> Ein Cookie ist eine kleine Datei, die auf Ihrem Gerät platziert wird. Sie können Ihren Browser anweisen, alle Cookies abzulehnen oder anzuzeigen, wenn ein Cookie gesendet wird. Wenn Sie jedoch keine Cookies akzeptieren, können Sie möglicherweise nicht alle Teile unseres Dienstes nutzen. Sofern Sie Ihre Browsereinstellungen nicht so angepasst haben, dass Cookies abgelehnt werden, kann unser Dienst Cookies verwenden.</li>
    <li><b>Web Beacons.</b> Einige Abschnitte unseres Dienstes und unsere E-Mails können kleine elektronische Dateien enthalten, die als Web Beacons bekannt sind (auch bezeichnet als Clear Gifs, Pixel-Tags und Single-Pixel-Gifs), die es dem Unternehmen beispielsweise ermöglichen, Nutzer zu zählen, die diese Seiten besucht oder eine E-Mail geöffnet haben, und andere verwandte Website-Statistiken (wie die Beliebtheit eines bestimmten Abschnitts und die Überprüfung der System- und Serverintegrität).</li></ul>
    <p>Cookies können "persistent" (dauerhaft) oder "session-based" (sitzungsbasiert) sein. Persistente Cookies verbleiben auf Ihrem persönlichen Computer oder mobilen Gerät, wenn Sie offline gehen, während Sitzungscookies gelöscht werden, sobald Sie Ihren Webbrowser schließen.</p>
    <p>Wir verwenden sowohl Sitzungs- als auch persistente Cookies zu den unten beschriebenen Zwecken:</p>
    <ul><li><b>Notwendige/essentielle Cookies</b>Art: Sitzungscookies Verwaltet von: Uns Zweck: Diese Cookies sind wesentlich, um Ihnen die über die Website verfügbaren Dienste zu bieten und einige ihrer Funktionen zu nutzen. Sie helfen, Benutzer zu authentifizieren und betrügerische Nutzung von Benutzerkonten zu verhindern. Ohne diese Cookies können die von Ihnen angeforderten Dienste nicht bereitgestellt werden, und wir verwenden diese Cookies nur, um Ihnen diese Dienste zur Verfügung zu stellen.</li>
    <li><b>Cookies-Richtlinie/Hinweis Akzeptanz Cookies</b> Art: Persistente Cookies Verwaltet von: Uns Zweck: Diese Cookies identifizieren, ob Benutzer die Verwendung von Cookies auf der Website akzeptiert haben.</li>
    <li><b>Funktionalitätscookies</b> Art: Persistente Cookies Verwaltet von: Uns Zweck: Diese Cookies ermöglichen es uns, sich an Entscheidungen zu erinnern, die Sie treffen, wenn Sie die Website nutzen, wie z.B. das Speichern Ihrer Anmeldedaten oder Sprachpräferenz. Der Zweck dieser Cookies ist es, Ihnen eine persönlichere Erfahrung zu bieten und zu vermeiden, dass Sie jedes Mal, wenn Sie die Website nutzen, Ihre Präferenzen erneut eingeben müssen.</li></ul>
    <p>Für weitere Informationen über die von uns verwendeten Cookies und Ihre Wahlmöglichkeiten bezüglich Cookies, besuchen Sie bitte unsere Cookie-Richtlinie oder den Cookie-Abschnitt unserer Datenschutzrichtlinie.</p>
    <h2>Verwendung Ihrer persönlichen Daten</h2>
    <p>Das Unternehmen kann personenbezogene Daten für die folgenden Zwecke verwenden:</p>
    <ul><li><b>Um unseren Dienst bereitzustellen und zu warten,</b> einschließlich der Überwachung der Nutzung unseres Dienstes.</li>
    <li><b>Zur Verwaltung Ihres Kontos:</b> um Ihre Registrierung als Benutzer des Dienstes zu verwalten. Die von Ihnen bereitgestellten personenbezogenen Daten können Ihnen Zugang zu verschiedenen Funktionalitäten des Dienstes gewähren, die Ihnen als registriertem Benutzer zur Verfügung stehen.</li>
    <li><b>Zur Vertragserfüllung:</b> die Entwicklung, Einhaltung und Durchführung des Kaufvertrags für die Produkte, Artikel oder Dienstleistungen, die Sie gekauft haben, oder jedes andere Vertragsverhältnis mit uns über den Dienst.</li>
    <li><b>Um Sie zu kontaktieren:</b> Sie per E-Mail, Telefonanrufe, SMS oder andere äquivalente Formen der elektronischen Kommunikation zu erreichen, wie z. B. Push-Benachrichtigungen von mobilen Anwendungen bezüglich Aktualisierungen oder informativer Mitteilungen im Zusammenhang mit Funktionalitäten, Produkten oder beauftragten Dienstleistungen, einschließlich notwendiger Sicherheitsupdates.</li>
    <li><b>Um Ihre Anfragen zu verwalten:</b> Ihre Anfragen an uns zu besuchen und zu verwalten.</li>
    <li><b>Für Geschäftsübertragungen:</b> Wir können Ihre Informationen verwenden, um eine Fusion, Veräußerung, Restrukturierung, Reorganisation, Auflösung oder einen anderen Verkauf oder Transfer einiger oder aller unserer Vermögenswerte zu bewerten oder durchzuführen, ob als laufendes Unternehmen oder als Teil eines Insolvenzverfahrens, Liquidation oder ähnlichen Verfahrens, bei dem von uns gehaltene personenbezogene Daten über unsere Dienstnutzer zu den übertragenen Vermögenswerten gehören.</li>
    <li><b>Für andere Zwecke:</b> Wir können Ihre Informationen für andere Zwecke verwenden, wie Datenanalyse, Identifizierung von Nutzungstrends, Bestimmung der Effektivität unserer Werbekampagnen und zur Bewertung und Verbesserung unseres Dienstes, unserer Produkte, unseres Marketings und Ihrer Erfahrung.</li></ul>
    <p>Wir können Ihre persönlichen Informationen in den folgenden Situationen teilen:</p>
    <ul><li><b>Mit Dienstleistern: Wir können Ihre persönlichen Informationen mit Dienstleistern teilen, um die Nutzung unseres Dienstes zu überwachen und zu analysieren und um mit Ihnen in Kontakt zu treten.</li>
    <li><b>Für Geschäftsübertragungen:</b> Wir können Ihre persönlichen Informationen im Zusammenhang mit oder während der Verhandlungen einer Fusion, des Verkaufs von Unternehmensvermögen, der Finanzierung oder der Akquisition von ganz oder einem Teil unseres Geschäfts an ein anderes Unternehmen teilen oder übertragen.</li>
    <li><b>Mit verbundenen Unternehmen:</b> Wir können Ihre Informationen mit unseren verbundenen Unternehmen teilen, in welchem Fall wir von diesen verbundenen Unternehmen verlangen, diese Datenschutzrichtlinie zu ehren. Zu den verbundenen Unternehmen gehören unser Mutterunternehmen und alle anderen Tochtergesellschaften, Joint-Venture-Partner oder andere Unternehmen, die wir kontrollieren oder die unter gemeinsamer Kontrolle mit uns stehen.</li>
    <li><b>Mit Geschäftspartnern:</b> Wir können Ihre Informationen mit unseren Geschäftspartnern teilen, um Ihnen bestimmte Produkte, Dienstleistungen oder Werbeaktionen anzubieten.</li>
    <li><b>Mit anderen Benutzern:</b> Wenn Sie persönliche Informationen teilen oder anderweitig in öffentlichen Bereichen mit anderen Benutzern interagieren, können solche Informationen von allen Benutzern eingesehen und möglicherweise öffentlich außerhalb verteilt werden.</li>
    <li><b>Mit Ihrer Zustimmung:</b> Wir können Ihre persönlichen Informationen für jeden anderen Zweck mit Ihrer Zustimmung offenlegen.</li></ul>
    <h2>Aufbewahrung Ihrer persönlichen Daten</h2>
    <p>Das Unternehmen wird Ihre persönlichen Daten nur so lange aufbewahren, wie es für die in dieser Datenschutzrichtlinie dargelegten Zwecke notwendig ist. Wir werden Ihre persönlichen Daten in dem Maße aufbewahren und verwenden, wie es zur Erfüllung unserer rechtlichen Verpflichtungen notwendig ist (zum Beispiel, wenn wir Ihre Daten aufbewahren müssen, um geltenden Gesetzen zu entsprechen), Streitigkeiten beizulegen und unsere rechtlichen Vereinbarungen und Richtlinien durchzusetzen.</p>
    <p>Das Unternehmen wird auch Nutzungsdaten für interne Analysezwecke aufbewahren. Nutzungsdaten werden im Allgemeinen für einen kürzeren Zeitraum aufbewahrt, es sei denn, diese Daten werden verwendet, um die Sicherheit zu stärken oder die Funktionalität unseres Dienstes zu verbessern, oder wir sind rechtlich verpflichtet, diese Daten für längere Zeiträume aufzubewahren.</p>
    <h2>Übertragung Ihrer persönlichen Daten</h2>
    <p>Ihre Informationen, einschließlich persönlicher Daten, werden in den Betriebsbüros des Unternehmens und an allen anderen Orten verarbeitet, an denen die an der Verarbeitung beteiligten Parteien sich befinden. Dies bedeutet, dass diese Informationen auf Computer übertragen und auf diesen aufrechterhalten werden können, die sich außerhalb Ihres Staates, Ihrer Provinz, Ihres Landes oder einer anderen staatlichen Gerichtsbarkeit befinden, in denen die Datenschutzgesetze von denen Ihrer Gerichtsbarkeit abweichen können.</p>
    <p>Ihre Zustimmung zu dieser Datenschutzrichtlinie, gefolgt von Ihrer Übermittlung solcher Informationen, stellt Ihre Zustimmung zu dieser Übertragung dar. Das Unternehmen wird alle vernünftigerweise notwendigen Schritte unternehmen, um sicherzustellen, dass Ihre Daten sicher behandelt werden und in Übereinstimmung mit dieser Datenschutzrichtlinie, und keine Übertragung Ihrer persönlichen Daten an eine Organisation oder ein Land stattfindet, es sei denn, es sind angemessene Kontrollen einschließlich der Sicherheit Ihrer Daten und anderer persönlicher Informationen vorhanden.</p>
    <h2>Löschung Ihrer persönlichen Daten</h2>
    <p>Sie haben das Recht, die Löschung Ihrer persönlichen Daten zu verlangen oder unsere Unterstützung bei der Löschung der über Sie gesammelten persönlichen Daten zu erbitten.</p>
    <p>Unser Dienst kann es Ihnen ermöglichen, bestimmte Informationen über sich selbst innerhalb des Dienstes zu löschen.</p>
    <p>Sie können Ihre Informationen jederzeit aktualisieren, ändern oder löschen, indem Sie sich in Ihr Konto einloggen (falls vorhanden) und den Abschnitt Kontoeinstellungen aufrufen, um Ihre persönlichen Informationen zu verwalten. Sie können uns auch kontaktieren, um Zugang zu erhalten oder Korrekturen oder die Löschung jeglicher persönlicher Informationen, die Sie uns zur Verfügung gestellt haben, zu erbitten.</p>
    <p>Bitte beachten Sie jedoch, dass wir bestimmte Informationen aufbewahren müssen, wenn wir eine rechtliche Verpflichtung oder eine rechtmäßige Grundlage dazu haben.</p>
    <h2>Offenlegung Ihrer persönlichen Daten</h2>
    <h3>Geschäftstransaktionen</h3>
    <p>Wenn das Unternehmen in eine Fusion, Akquisition oder einen Vermögensverkauf verwickelt ist, können Ihre persönlichen Daten übertragen werden. Wir werden vor der Übertragung Ihrer persönlichen Daten und bevor sie einer anderen Datenschutzrichtlinie unterliegen, eine Benachrichtigung bereitstellen.</p>
    <h3>Strafverfolgung</h3>
    <p>Unter bestimmten Umständen kann das Unternehmen verpflichtet sein, Ihre persönlichen Daten offen zu legen, wenn dies gesetzlich erforderlich ist oder auf gültige Anfragen von öffentlichen Behörden (z.B. ein Gericht oder eine Regierungsbehörde) reagiert werden muss.</p>
    <h3>Andere rechtliche Anforderungen</h3>
    <p>Das Unternehmen kann Ihre persönlichen Daten in dem guten Glauben offenlegen, dass eine solche Aktion notwendig ist, um:</p>
    <ul><li>einer rechtlichen Verpflichtung nachzukommen</li>
    <li>die Rechte oder das Eigentum des Unternehmens zu schützen und zu verteidigen</li>
    <li>mögliches Fehlverhalten im Zusammenhang mit dem Dienst zu verhindern oder zu untersuchen</li>
    <li>die persönliche Sicherheit der Benutzer des Dienstes oder der Öffentlichkeit zu schützen</li>
    <li>sich gegen rechtliche Haftung zu schützen</li></ul>
    <h2>Sicherheit Ihrer persönlichen Daten</h2>
    <p>Die Sicherheit Ihrer persönlichen Daten ist uns wichtig, aber denken Sie daran, dass keine Methode der Übertragung über das Internet oder Methode der elektronischen Speicherung 100% sicher ist. Während wir uns bemühen, kommerziell akzeptable Mittel zum Schutz Ihrer persönlichen Daten zu verwenden, können wir deren absolute Sicherheit nicht garantieren.</p>
    <h1>Datenschutz für Kinder</h1>
    <p>Unsere Dienste richten sich nicht an Personen unter 13 Jahren. Wir sammeln wissentlich keine persönlich identifizierbaren Informationen von Personen unter 13 Jahren. Wenn Sie ein Elternteil oder Erziehungsberechtigter sind und wissen, dass Ihr Kind uns persönliche Daten zur Verfügung gestellt hat, kontaktieren Sie uns bitte. Wenn wir feststellen, dass wir personenbezogene Daten von Personen unter 13 Jahren ohne Überprüfung der elterlichen Zustimmung gesammelt haben, werden wir Schritte unternehmen, um diese Informationen von unseren Servern zu löschen.</p>
    <p>Wenn wir uns auf die Einwilligung als rechtliche Grundlage für die Verarbeitung Ihrer Informationen stützen müssen und Ihr Land die Zustimmung der Eltern erfordert, benötigen wir möglicherweise die Zustimmung Ihrer Eltern, bevor wir diese Informationen sammeln und verwenden.</p>
    <h1>Links zu anderen Websites</h1>
    <p>Unser Dienst kann Links zu anderen Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen Link eines Drittanbieters klicken, werden Sie zu dessen Website weitergeleitet. Wir empfehlen Ihnen dringend, die Datenschutzrichtlinie jeder Website, die Sie besuchen, zu überprüfen.</p>
    <p>Wir haben keine Kontrolle über und übernehmen keine Verantwortung für den Inhalt, die Datenschutzrichtlinien oder Praktiken von Websites oder Diensten Dritter.</p>
    <h1>Änderungen der Datenschutzrichtlinie</h1>
    <p>Wir können unsere Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir werden Sie über Änderungen informieren, indem wir die neue Datenschutzrichtlinie auf dieser Seite veröffentlichen.</p>
    <p>Wir werden Sie per E-Mail und/oder durch einen auffälligen Hinweis auf unserem Dienst vor dem Inkrafttreten der Änderungen informieren und das Datum der "Letzten Aktualisierung" am Anfang dieser Datenschutzrichtlinie aktualisieren.</p>
    <p>Es wird empfohlen, diese Datenschutzrichtlinie regelmäßig zu überprüfen, um über eventuelle Änderungen informiert zu sein. Änderungen an dieser Datenschutzrichtlinie werden wirksam, wenn sie auf dieser Seite veröffentlicht werden.</p>
    <h1>Kontaktieren Sie uns</h1>
    <p>Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben, können Sie uns kontaktieren:</p>
    <ul><li>Per E-Mail: <a link="aipoemgenerator@outlook.com">aipoemgenerator@outlook.com</a></li></ul>`,
  },
  it: {
    header_title:"Generatore di poesie - Crea poesie in rima con l'AI gratuito",
    Description:"Un generatore gratuito di poesie AI per creare poesie in rima in pochi secondi. Esplora il nostro Generatore di Poesie AI: crea poesie personalizzate su qualsiasi tema.",
    "poemai_title": "Generatore di poesie",
    "poemai_input_title": "Generatore di poesie",
    "poemai_input_subtitle": "Genera una poesia su...",
    "poemai_input_tips": "Baci sotto la pioggia",
    "poemai_generate_btn": "Genera",
    "poemai_powered_by_gpt": "Alimentato da ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Errore di rete. Riprova per favore",
    "poemai_server_err_toast": "Errore del server, riprova",
    "poemai_generated_failed_toast": "Generazione della poesia fallita, riprova",
    "poemai_generated_poem": "Poesia generata",
    "poemai_copy_btn": "Copia",
    "poemai_copy_success_toast": "Copiato con successo",
    "poemai_privacy": "Politica sulla privacy",
    poemai_title_generate:"Generare",
    poemai_fv_theme:"Di cosa parla la poesia?",privacyContent:``,
  },
  pt: {
    header_title:"Gerador de Poemas - Crie um poema rimado com a mágica AI gratuita",
    Description:"Gerador de poemas AI gratuito: crie poemas rimados em segundos. Explore nosso Gerador de Poemas AI: Crie poemas rimados e personalizados sobre qualquer assunto.",
    "poemai_title": "Gerador de Poemas",
    "poemai_input_title": "Gerador de Poemas",
    "poemai_input_subtitle": "Gerar um poema sobre...",
    "poemai_input_tips": "Dança das flores silvestres",
    "poemai_generate_btn": "Gerar",
    "poemai_powered_by_gpt": "Alimentado por ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Erro de rede. Tente novamente",
    "poemai_server_err_toast": "Erro no servidor, tente novamente",
    "poemai_generated_failed_toast": "Falha ao gerar poema, tente novamente",
    "poemai_generated_poem": "Poema Gerado",
    "poemai_copy_btn": "Copiar",
    "poemai_copy_success_toast": "Copiado com sucesso",
    "poemai_privacy": "Política de privacidade",
    poemai_title_generate:"Gerar",
    poemai_fv_theme:"Sobre o que é o poema?",privacyContent:``,
  },
  es: {
    header_title:"Generador de poemas - crea poemas que riman con AI Magic gratis",
    Description:"Generador de poemas AI gratuito: crea poemas rimados en segundos. Explora nuestro Generador de Poemas AI: Crea poemas rimados y personalizados sobre cualquier tema.",
    "poemai_title": "Generador de Poemas",
    "poemai_input_title": "Generador de Poemas",
    "poemai_input_subtitle": "Generar un poema sobre...",
    "poemai_input_tips": "Voces del bosque antiguo",
    "poemai_generate_btn": "Generar",
    "poemai_powered_by_gpt": "Impulsado por ChatGPT",
    "poemai_thinking_status": "Pensando...",
    "poemai_network_err_toast": "Error de red. Intente de nuevo por favor",
    "poemai_server_err_toast": "Error de servidor, intenta de nuevo",
    "poemai_generated_failed_toast": "Error al generar el poema, intenta de nuevo",
    "poemai_generated_poem": "Poema Generado",
    "poemai_copy_btn": "Copiar",
    "poemai_copy_success_toast": "Copiado con éxito",
    "poemai_privacy": "Política de privacidad",
    poemai_title_generate:"Generar",
    poemai_fv_theme:"¿De qué trata el poema?",privacyContent:``,
  }
}


const i18n = createI18n({
  locale: 'en', // 默认语言
  fallbackLocale: 'en',
  messages,
});

export default i18n;